### ISSUE TITLE
Wrong message and weird output path

### ISSUE THREAD

**Issue by gharehyazie** [IngoScholtes/TemporalNetworks#1]
When you type "tempnet example" you expect a message like:
Usage: TempNet example [output_file]
while the actual message being displayed is:
Usage: TempNet cex [output_file]

cex should be renamed to example.

Also the output path of tempnet was set to "../../bin" wich is not only weird, but inconsistent with the screenshot you have put in the project page.
I wanted to fix these but I thought you might not like it. I would be more than happy to contribute to your project if you like.

Regards

**Comment by IngoScholtes** [comment]
Hi

Thanks a lot for your messages and for highlighting these issues. I will fix it asap. And please feel free to fork the project and send a corresponding pull request. 

Best, 

Ingo

**Comment by IngoScholtes** [comment]
Fixed in latest version
