### ISSUE TITLE
tikz generator problem

### ISSUE THREAD

**Issue by gharehyazie** [IngoScholtes/TemporalNetworks#2]
the tikz generator does not generate proper tikz files. some of the problems I have found so far:
1. in lines like this:
   strB.AppendLine(" \node[ lbl]                     (" + v + "-0)   {$" + v + "$};");
   the \node will create text "ode" instead of "node". so it should be fixed to "\\node[lbl]..."
2. forgot to define a
   \newcounter{a}
3. at the end: \end{tikzpicture} } the final } seems to be extra

**Comment by IngoScholtes** [comment]
Thanks for pointing this out. 

I did not really test this function thoroughly. With your feedback, I am sure that it will be easy to fix this though. 

Best, 

Ingo

**Comment by gharehyazie** [comment]
I found several other tiny bugs in this file. I will send you a pull
request soon.

Regards

**Comment by IngoScholtes** [comment]
Thanks, you indeed fixed this with your pull request. 

In the latest version, I added a LaTeX preamble so the generated tex file can directly be compiled.
